# This is a basic workflow to help you get started with Actions

name: rootfs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 定义依赖安装步骤
env:
  DEPENDENCIES: build-essential gcc-aarch64-linux-gnu bc flex bison p7zip-full kmod bash cpio binutils tar git wget dpkg libssl-dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [6.7-working, 6.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt update && sudo apt install $DEPENDENCIES

      - name: Build kernel
        run: sudo sh nabu-kernel_build.sh ${{ matrix.version }}

      - name: Upload deb packages
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: xiaomi-nabu-debs_${{ matrix.version }}
          path: ${{ github.workspace }}/*.deb
          
  rootfs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: kernel
    strategy:
      matrix:
        desktop: [ubuntu-desktop, lomiri]
        kernel: [6.7-working, 6.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: xiaomi-nabu-debs*
      - name: Install Dependencies
        run: sudo apt update && sudo apt install $DEPENDENCIES

      - name: Prepare chroot environment
        run: |
          sudo mkdir -p rootdir/tmp
          sudo mkdir -p rootdir/var/lib/gdm
          sudo mount -t proc /proc rootdir/proc
          sudo mount -t sysfs /sys rootdir/sys
          sudo mount -o bind /dev rootdir/dev
          sudo mount -o bind /dev/pts rootdir/dev/pts

      - name: Build rootfs
        run: sudo sh nabu-rootfs_build.sh ${{ matrix.desktop }} ${{ matrix.kernel }}

      - name: Clean up chroot environment
        run: |
          sudo umount rootdir/sys || true
          sudo umount rootdir/proc || true
          sudo umount rootdir/dev/pts || true
          sudo umount rootdir/dev || true

      - name: Upload rootfs.7z
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: rootfs_${{ matrix.desktop }}_${{ matrix.kernel }}
          path: rootfs.7z
          compression-level: 0
